### ISSUE TITLE
This ain't workin bro

### ISSUE THREAD

**Issue by ptrckdev** [cbdavide/practice-contest#1]
this gets a Run Time Error for the second test case on kattis

**Comment by cbdavide** [comment]
What problem are you referring to ?
I have some problems that I hadn't been able to solve, but it is stated in the commit message of the solution.

**Comment by ptrckdev** [comment]
Divisor Problem, sorry first time writing an issue didn't realize what I am giving an issue to the whole repo not just 1 file haha.

sorry, I was just frustrated with this task and had to write some salty comment somewhere
have a nice day ^^

**Comment by cbdavide** [comment]
Don't worry, 

I solved the problem, finally!!
You can see the accepted solution here d6ef765b2a3a2797c127c81fc5b4d8a57ea333fc
